export const CREATE_RATING_SUCCESS="CREATE_REVIEW_SUCCESS";
export const CREATE_RATING_FAILURE="CREATE_REVIEW_FAILURE";
export const CREATE_RATING_REQUEST="CREATE_REVIEW_REQUEST";

export const GET_RATING_SUCCESS="GET_REVIEW_SUCCESS";
export const GET_RATING_FAILURE="GET_REVIEW_FAILURE";
export const GET_RATING_REQUEST="GET_REVIEW_REQUEST";
