export const CREATE_BOOKING_SUCCESS="CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAILURE="CREATE_BOOKING_FAILURE";
export const CREATE_BOOKING_REQUEST="CREATE_BOOKING_REQUEST";

export const GET_BOOKING_SUCCESS="GET_BOOKING_SUCCESS";
export const GET_BOOKING_FAILURE="GET_BOOKING_FAILURE";
export const GET_BOOKING_REQUEST="GET_BOOKING_REQUEST";

export const GET_HOST_BOOKINGS_SUCCESS="GET_HOST_BOOKINGS_SUCCESS";
export const GET_HOST_BOOKINGS_FAILURE="GET_HOST_BOOKINGS_FAILURE";
export const GET_HOST_BOOKINGS_REQUEST="GET_HOST_BOOKINGS_REQUEST";

export const GET_BOOKINGS_BY_ID_REQUEST = "GET_BOOKINGS_BY_ID_REQUEST";
export const GET_BOOKINGS_BY_ID_SUCCESS = "GET_BOOKINGS_BY_ID_SUCCESS";
export const GET_BOOKINGS_BY_ID_FAILURE = "GET_BOOKINGS_BY_ID_FAILURE";

export const GET_BOOKINGS_ID_REQUEST = "GET_BOOKINGS_BY_ID_REQUEST";
export const GET_BOOKINGS_ID_SUCCESS = "GET_BOOKINGS_BY_ID_SUCCESS";
export const GET_BOOKINGS_ID_FAILURE = "GET_BOOKINGS_BY_ID_FAILURE";

export const GET_DELETE_BOOKING_SUCCESS="GET_DELETE_BOOKING_SUCCESS";
export const GET_DELETE_BOOKING_FAILURE="GET_DELETE_BOOKING_FAILURE";
export const GET_DELETE_BOOKING_REQUEST="GET_DELETE_BOOKING_REQUEST";

export const GET_ALL_BOOKINGS_REQUEST = "GET_ALL_BOOKINGS_REQUEST";
export const GET_ALL_BOOKINGS_SUCCESS = "GET_ALL_BOOKINGS_SUCCESS";
export const GET_ALL_BOOKINGS_FAIL = "GET_ALL_BOOKINGS_FAIL";


