
export const FIND_LISTINGS_SUCCESS="FIND_LISTINGS_SUCCESS";
export const FIND_LISTINGS_FAILURE="FIND_LISTINGS_FAILURE";
export const FIND_LISTINGS_REQUEST="FIND_LISTINGS_REQUEST";
 
export const CREATE_LISTING_SUCCESS="CREATE_LISTING_SUCCESS";
export const CREATE_LISTING_FAILURE="CREATE_LISTING_FAILURE";
export const CREATE_LISTING_REQUEST="CREATE_LISTING_REQUEST";

export const GET_LISTING_SUCCESS="GET_LISTING_SUCCESS";
export const GET_LISTING_FAILURE="GET_LISTING_FAILURE";
export const GET_LISTING_REQUEST="GET_LISTING_REQUEST";
 
export const UPDATE_LISTING_SUCCESS="UPDATE_LISTING_SUCCESS";
export const UPDATE_LISTING_FAILURE="UPDATE_LISTING_FAILURE";
export const UPDATE_LISTING_REQUEST="UPDATE_LISTING_REQUEST";
 
export const DELETE_LISTING_SUCCESS="DELETE_LISTING_SUCCESS";
export const DELETE_LISTING_FAILURE="DELETE_LISTING_FAILURE";
export const DELETE_LISTING_REQUEST="DELETE_LISTING_REQUEST";

export const GET_LISTING_BY_ID_SUCCESS="GET_LISTING_BY_ID_SUCCESS";
export const GET_LISTING_BY_ID_FAILURE="GET_LISTING_BY_ID_FAILURE";
export const GET_LISTING_BY_ID_REQUEST="GET_LISTING_BY_ID_REQUEST";

export const GET_ALL_LISTINGS_SUCCESS="GET_ALL_LISTINGS_SUCCESS";
export const GET_ALL_LISTINGS_FAILURE="GET_ALL_LISTINGS_FAILURE";
export const GET_ALL_LISTINGS_REQUEST="GET_ALL_LISTINGS_REQUEST";